### ISSUE TITLE
Add ability to show loader on AsyncReplaceRegion

### ISSUE THREAD

**Issue by just-boris** [ftdebugger/regions-extras#6]
Now `AsyncReplaceRegion` just waits until promise will be settled until instantiation.
It would be nice to see loader while promise is pending.

I propose to put loader inside the helper block.
```
    {{#region "content" async=true}}
        <div class="loader_container">
            <div class="spinner spinner_size_XL">
                <div class="spinner__circle"></div>
            </div>
        </div>
    {{/region}}
```
This content will be shown until promise has been resolved and then ready view will replace it.

**Comment by ftdebugger** [comment]
Block template often use to inject dependencies into view. For example https://github.com/ftdebugger/injectify-view can do something like this:

```hbs
{{#view "./SomeWrapper"}}
    <div class="date">{{../date}}</div>
{{/view}}
```

and in `SomeWrapper.hbs`:

```handlebars
<div class="wrapper">
    <div class="wrapper__i">{{{content}}}</div>
</div>
```

For this purpose you can create new type of region, which will be insert loader while view fullfilling
